name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm i
    - run: |
        echo ">>> Start compile autohotkey plus."
        npm run build
        echo ">>> Compile autohotkey plus sucess!"
